<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'PS_EdUnd');
define('_DB_USER_', 'root');
define('_DB_PASSWD_', 'root');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', '3fA5VxRJytADqrQ89ZXfVdoBkiyS30KEoHs8xzxxjUduMW60bHjC3niz');
define('_COOKIE_IV_', 'AvpoZ5PX');
define('_PS_CREATION_DATE_', '2014-09-28');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', 'NM8POcRWqvTLwScp2wcIBnCixxGJ1e0n');
define('_RIJNDAEL_IV_', 'gfMN3AGdW7rpPf5jfDamaw==');
